"""
Structured query tool for Arknights data.
Allows LLM to query operator/enemy data via SQL on pre-built SQLite tables.
"""

import json
import sqlite3
import logging
import re
from pathlib import Path
from typing import Dict, Any, List

logger = logging.getLogger(__name__)

# Path to the SQLite database
DB_PATH = Path(__file__).parent.parent.parent / "data" / "arknights_structured.db"

# Schema description given to the LLM
SCHEMA_DESCRIPTION = """
## operators 表（干员数据）
| 列名 | 类型 | 说明 |
|------|------|------|
| id | INTEGER | 主键 |
| name | TEXT | 干员名 |
| name_en | TEXT | 干员外文名 |
| rarity | INTEGER | 星级 (1-6) |
| class | TEXT | 职业（近卫/狙击/重装/术师/医疗/辅助/特种/先锋） |
| branch | TEXT | 分支（如 无畏者/领主/剑豪 等） |
| trait | TEXT | 特性描述 |
| faction | TEXT | 所属势力 |
| obtain_method | TEXT | 获得方式 |
| artist | TEXT | 画师 |
| cv_cn | TEXT | 中文配音 |
| cv_jp | TEXT | 日文配音 |
| cv_en | TEXT | 英文配音 |
| hp_elite2 | INTEGER | 精英2满级生命上限 |
| atk_elite2 | INTEGER | 精英2满级攻击力 |
| def_elite2 | INTEGER | 精英2满级防御力 |
| mres_elite2 | INTEGER | 精英2满级法术抗性 |
| redeploy_time | TEXT | 再部署时间 |
| dp_cost | TEXT | 部署费用 |
| block_count | INTEGER | 阻挡数 |
| attack_speed | TEXT | 攻击速度 |
| release_date | TEXT | 上线时间 |

## enemies 表（敌人数据）
| 列名 | 类型 | 说明 |
|------|------|------|
| id | INTEGER | 主键 |
| name | TEXT | 名称 |
| enemy_index | TEXT | 敌人索引 |
| category | TEXT | 种类 |
| rank | TEXT | 地位级别（普通/精英/领袖） |
| attack_type | TEXT | 攻击类型（近战/远程） |
| damage_type | TEXT | 伤害类型（物理/法术） |
| movement | TEXT | 行动方式（地面/飞行） |
| description | TEXT | 描述 |
| ability | TEXT | 能力描述 |
| stages | TEXT | 出场关卡 |
| hp | INTEGER | 最大生命值 |
| atk | INTEGER | 攻击力 |
| def | INTEGER | 防御力 |
| mres | INTEGER | 法术抗性 |
| move_speed | REAL | 移动速度 |
| attack_interval | REAL | 攻击间隔 |

查询提示：
- 字符串匹配使用 LIKE '%keyword%' 或 = 'exact'
- 数值比较使用 >、<、>=、<=、=
- 排序使用 ORDER BY column ASC/DESC
- 限制结果数使用 LIMIT N
- 计数使用 COUNT(*)
- 分组使用 GROUP BY
- 示例：SELECT name, rarity, atk_elite2 FROM operators WHERE class='近卫' AND atk_elite2 > 700 ORDER BY atk_elite2 DESC
- 示例：SELECT name, hp, atk, def FROM enemies WHERE rank='领袖' ORDER BY hp DESC LIMIT 10
"""

MAX_ROWS = 50  # Maximum rows to return

# Whitelist: only these tables are allowed in queries
ALLOWED_TABLES = {"operators", "enemies"}

# Dangerous SQL patterns (checked case-insensitively after stripping comments)
_DANGEROUS_RE = re.compile(
    r'\b(DROP|DELETE|UPDATE|INSERT|ALTER|CREATE|EXEC|EXECUTE|ATTACH|DETACH|PRAGMA|'
    r'GRANT|REVOKE|TRUNCATE|REINDEX|VACUUM)\b',
    re.IGNORECASE,
)


def _clean_sql(sql: str) -> str:
    """Validate and sanitize an LLM-generated SQL query.

    - Only SELECT statements are allowed.
    - Dangerous keywords (DROP, DELETE, etc.) are blocked via precompiled regex.
    - Table names are checked against an allowlist.
    - A LIMIT clause is enforced if missing.
    """
    cleaned = sql.strip()
    # Remove markdown code blocks if present
    cleaned = re.sub(r'^```(?:sql)?\s*\n?', '', cleaned)
    cleaned = re.sub(r'\n?```\s*$', '', cleaned)
    cleaned = cleaned.strip()

    # Only allow SELECT
    if not re.match(r'^\s*SELECT\b', cleaned, re.IGNORECASE):
        raise ValueError("只允许 SELECT 查询")

    # Block dangerous keywords via precompiled regex
    match = _DANGEROUS_RE.search(cleaned)
    if match:
        raise ValueError(f"不允许使用 {match.group(0)} 操作")

    # Validate table names against allowlist
    # Extract table names after FROM and JOIN clauses
    table_refs = re.findall(
        r'(?:FROM|JOIN)\s+(\w+)',
        cleaned, re.IGNORECASE,
    )
    for tbl in table_refs:
        if tbl.lower() not in ALLOWED_TABLES:
            raise ValueError(f"不允许查询表 '{tbl}'，只允许 {', '.join(sorted(ALLOWED_TABLES))} 表")

    # Enforce LIMIT
    if not re.search(r'\bLIMIT\b', cleaned, re.IGNORECASE):
        cleaned += f" LIMIT {MAX_ROWS}"

    return cleaned


async def execute_structured_query(arguments: Dict[str, Any], session_id: str = "") -> Dict:
    """Execute arknights_structured_query tool.

    The SQL query is generated by the LLM based on the schema description.
    Returns {columns: [...], rows: [...], row_count: N, sql: "..."}
    """
    sql = arguments.get("sql", "")
    if not sql:
        return {"error": "sql parameter is required", "schema": SCHEMA_DESCRIPTION}

    try:
        cleaned_sql = _clean_sql(sql)
    except ValueError as e:
        return {"error": str(e), "schema": SCHEMA_DESCRIPTION}

    if not DB_PATH.exists():
        return {"error": "结构化数据库未初始化，请先运行数据同步脚本"}

    try:
        with sqlite3.connect(str(DB_PATH)) as conn:
            conn.row_factory = sqlite3.Row
            cursor = conn.execute(cleaned_sql)
            rows = [dict(row) for row in cursor.fetchall()]
            columns = [desc[0] for desc in cursor.description] if cursor.description else []

            return {
                "columns": columns,
                "rows": rows,
                "row_count": len(rows),
                "sql": cleaned_sql,
            }
    except sqlite3.OperationalError as e:
        return {"error": f"SQL 执行错误: {str(e)}. 请检查表名是否正确。", "schema": SCHEMA_DESCRIPTION}
    except Exception as e:
        logger.error(f"Structured query failed: {e}", exc_info=True)
        return {"error": f"查询失败: {str(e)}"}
